# Generated by Django 4.2 on 2025-04-30 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('resumemanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeshortlisting',
            name='hr_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.organization'),
        ),
        migrations.AddField(
            model_name='resumeanalysis',
            name='recruiter_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.candidate'),
        ),
    ]
