# Generated by Django 4.2 on 2025-04-30 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_initial'),
        ('user', '0001_initial'),
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobalert',
            name='cand_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.candidate'),
        ),
        migrations.AddField(
            model_name='jobalert',
            name='job_alert_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job'),
        ),
    ]
